using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using AgateLib.Geometry;

namespace AgateLib.AudioLib 
{
	/// <summary>
	/// Class which can be used to query information about what features are supported
	/// by the audio driver.
	/// </summary>
	public class AudioCapsInfo
	{
		internal AudioCapsInfo()
		{ }

		/// <summary>
		/// Indicates whether or not the application can stream audio to the
		/// audio system by creating a StreamingSoundBuffer.
		/// </summary>
		public bool SupportsStreamingAudio
		{
			get { return Audio.Impl.CapsBool(AudioBoolCaps.StreamingSoundBuffer); }
		}
	}

	/// <summary>
	/// Testable boolean capabilities.
	/// </summary>
	public enum AudioBoolCaps
	{
		/// <summary>
		/// Indicates whether or not the audio driver supports streaming audio
		/// generated by the application.
		/// </summary>
		StreamingSoundBuffer,
	}
}
